/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 */

plugins {
    id("maven-publish")
    id("java-gradle-plugin")
    id("org.jetbrains.kotlin.jvm") version("1.9.10")
}

version = "0.5.0"
group = "com.fussionlabs.gradle"

repositories {
    mavenLocal()
    mavenCentral()
}

kotlin {
    jvmToolchain {
        languageVersion.set(JavaLanguageVersion.of(JavaVersion.VERSION_1_8.majorVersion))
    }
}

gradlePlugin {
    plugins {
        create("go-plugin") {
            id = "com.fussionlabs.gradle.go-plugin"
            implementationClass = "com.fussionlabs.gradle.GoPlugin"
        }
    }
}